version: '3'
services:
  nodejs:
    image: node:9@sha256:66c14485aa09d55b8707c062093fc0700c97e18780b98c5089502d7eee89e351
    container_name: "zola-node"
    working_dir: /zola-api
    ports:
      - "3001:3001"
    links:
      - "postgres:postgres.host"
    volumes:
      - "${APP_DIR}:/zola-api:rw"
    environment:
      - NODE_ENV
      - NO_DEBUG
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    entrypoint: /bin/bash /zola-api/docker/node/entrypoint.sh
    restart: always
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-node"

  postgres:
    image: postgres:10@sha256:852dd8150c5ea73015cf2c9c601de07113c31b3272628f9a945d46c7d960004d
    container_name: "zola-postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-postgres"
