version: '3'
services:
  nodejs:
    image: node:9@sha256:bd7b9aaf77ab2ce1e83e7e79fc0969229214f9126ced222c64eab49dc0bdae90
    container_name: "zola-node"
    working_dir: /zola-api
    ports:
      - "3001:3001"
    links:
      - "postgres:postgres.host"
      - "redis:redis.host"
    volumes:
      - "${APP_DIR}:/zola-api:rw"
    environment:
      - NODE_ENV
      - NO_DEBUG
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SENDGRID_API_KEY
    entrypoint: /bin/bash /zola-api/docker/node/entrypoint.sh
    restart: always
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-node"

  postgres:
    image: postgres:10@sha256:3913a8fc7efb82eecf9c1b0085145bf6be78076e03e85cd049ba0b4da00a94b1
    container_name: "zola-postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-postgres"


  redis:
    image: redis:4.0-alpine@sha256:8782054ba81c3b8b969dae4822263a97fc241a06f8f1fe1acacd7c077ec60831
    container_name: "zola-redis"
    restart: always
    volumes:
      - "${REDIS_DATA_DIR}:/data"
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-redis"
