version: '3'
services:
  zola-api:
    image: node:9@sha256:a18dcc02ca8e3eedd1b41a4085c3c506d785081e19c88df42f1c0c2ecdb098fc
    container_name: "zola-api"
    working_dir: /zola-api
    ports:
      - "3001:3001"
    links:
      - "zola-postgres:postgres.host"
    volumes:
      - "${APP_DIR}:/zola-api:rw"
    environment:
      - NODE_ENV
      - NO_DEBUG
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    entrypoint: /bin/bash /zola-api/docker/node/entrypoint.sh
    restart: always
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-node"

  zola-postgres:
    image: postgres:10@sha256:e033c99282a81622b1eed36b735034e10d633a34cca3387f6142381770cfbcc8
    container_name: "zola-postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-postgres"
