version: '3'
services:
  nodejs:
    image: node:9@sha256:f1d26f827bb796baf568203f8d42c20cb59fb55a81ab35de3d1dd09dd010c816
    container_name: "zola-node"
    working_dir: /zola-api
    ports:
      - "3001:3001"
    links:
      - "postgres:postgres.host"
      - "redis:redis.host"
    volumes:
      - "${APP_DIR}:/zola-api:rw"
    environment:
      - NODE_ENV
      - NO_DEBUG
      - POSTGRES_HOST
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SENDGRID_API_KEY
    entrypoint: /bin/bash /zola-api/docker/node/entrypoint.sh
    restart: always
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-node"

  postgres:
    image: postgres:10@sha256:1c2cc88d0573332ff1584f72f0cf066b1db764166786d85f5541b3fc1e362aee
    container_name: "zola-postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-postgres"


  redis:
    image: redis:4.0-alpine@sha256:aab35d6ec4c49ef5c1674f0582eeb2f6e90ee0fd3010d8a806d8833f36cc0525
    container_name: "zola-redis"
    restart: always
    volumes:
      - "${REDIS_DATA_DIR}:/data"
    # logging:
    #   driver: "syslog"
    #   options:
    #     syslog-facility: "local0"
    #     tag: "zola-redis"
