// flow-typed signature: 4044c5e2ed2d8301cc06bfa29e6912ad
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-modules-commonjs_v6.26.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-modules-commonjs' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-modules-commonjs/lib/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-modules-commonjs/lib/index.js' {
  declare module.exports: $Exports<
    'babel-plugin-transform-es2015-modules-commonjs/lib/index'
  >
}
