// flow-typed signature: 1bf865b4cb22f4a984c52c4b72adb8a3
// flow-typed version: <<STUB>>/redis-mock_v0.21.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redis-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redis-mock' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redis-mock/lib/hash' {
  declare module.exports: any
}

declare module 'redis-mock/lib/helpers' {
  declare module.exports: any
}

declare module 'redis-mock/lib/item' {
  declare module.exports: any
}

declare module 'redis-mock/lib/keys' {
  declare module.exports: any
}

declare module 'redis-mock/lib/list' {
  declare module.exports: any
}

declare module 'redis-mock/lib/multi' {
  declare module.exports: any
}

declare module 'redis-mock/lib/pubsub' {
  declare module.exports: any
}

declare module 'redis-mock/lib/redis-mock' {
  declare module.exports: any
}

declare module 'redis-mock/lib/server' {
  declare module.exports: any
}

declare module 'redis-mock/lib/set' {
  declare module.exports: any
}

declare module 'redis-mock/lib/sortedset' {
  declare module.exports: any
}

declare module 'redis-mock/lib/strings' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.connection.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.hash.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.helpers.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.item.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.keys.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.list.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.multi' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.pubsub.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.server.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.set.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.sortedset.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.strings.test' {
  declare module.exports: any
}

declare module 'redis-mock/test/redis-mock.test' {
  declare module.exports: any
}

// Filename aliases
declare module 'redis-mock/lib/hash.js' {
  declare module.exports: $Exports<'redis-mock/lib/hash'>
}
declare module 'redis-mock/lib/helpers.js' {
  declare module.exports: $Exports<'redis-mock/lib/helpers'>
}
declare module 'redis-mock/lib/item.js' {
  declare module.exports: $Exports<'redis-mock/lib/item'>
}
declare module 'redis-mock/lib/keys.js' {
  declare module.exports: $Exports<'redis-mock/lib/keys'>
}
declare module 'redis-mock/lib/list.js' {
  declare module.exports: $Exports<'redis-mock/lib/list'>
}
declare module 'redis-mock/lib/multi.js' {
  declare module.exports: $Exports<'redis-mock/lib/multi'>
}
declare module 'redis-mock/lib/pubsub.js' {
  declare module.exports: $Exports<'redis-mock/lib/pubsub'>
}
declare module 'redis-mock/lib/redis-mock.js' {
  declare module.exports: $Exports<'redis-mock/lib/redis-mock'>
}
declare module 'redis-mock/lib/server.js' {
  declare module.exports: $Exports<'redis-mock/lib/server'>
}
declare module 'redis-mock/lib/set.js' {
  declare module.exports: $Exports<'redis-mock/lib/set'>
}
declare module 'redis-mock/lib/sortedset.js' {
  declare module.exports: $Exports<'redis-mock/lib/sortedset'>
}
declare module 'redis-mock/lib/strings.js' {
  declare module.exports: $Exports<'redis-mock/lib/strings'>
}
declare module 'redis-mock/test/redis-mock.connection.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.connection.test'>
}
declare module 'redis-mock/test/redis-mock.hash.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.hash.test'>
}
declare module 'redis-mock/test/redis-mock.helpers.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.helpers.test'>
}
declare module 'redis-mock/test/redis-mock.item.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.item.test'>
}
declare module 'redis-mock/test/redis-mock.keys.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.keys.test'>
}
declare module 'redis-mock/test/redis-mock.list.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.list.test'>
}
declare module 'redis-mock/test/redis-mock.multi.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.multi'>
}
declare module 'redis-mock/test/redis-mock.pubsub.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.pubsub.test'>
}
declare module 'redis-mock/test/redis-mock.server.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.server.test'>
}
declare module 'redis-mock/test/redis-mock.set.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.set.test'>
}
declare module 'redis-mock/test/redis-mock.sortedset.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.sortedset.test'>
}
declare module 'redis-mock/test/redis-mock.strings.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.strings.test'>
}
declare module 'redis-mock/test/redis-mock.test.js' {
  declare module.exports: $Exports<'redis-mock/test/redis-mock.test'>
}
